#include "../mtlpp.hpp"
#include "window.hpp"

#if 1

mtlpp::Device              g_device;
mtlpp::CommandQueue        g_commandQueue;
mtlpp::Buffer              g_vertexBuffer;
mtlpp::Texture             g_texture;
mtlpp::RenderPipelineState g_renderPipelineState;

void Render(const Window& win)
{
    mtlpp::CommandBuffer commandBuffer = g_commandQueue.CommandBuffer();
    
    mtlpp::RenderPassDescriptor renderPassDesc = win.GetRenderPassDescriptor();
    if (renderPassDesc)
    {
        mtlpp::RenderCommandEncoder renderCommandEncoder = commandBuffer.RenderCommandEncoder(renderPassDesc);
        renderCommandEncoder.SetCullMode(mtlpp::CullMode::Back);
        renderCommandEncoder.SetRenderPipelineState(g_renderPipelineState);
        renderCommandEncoder.SetVertexBuffer(g_vertexBuffer, 0, 0);
        renderCommandEncoder.SetFragmentTexture(g_texture, 0);
        renderCommandEncoder.Draw(mtlpp::PrimitiveType::Triangle, 0, 3);
        renderCommandEncoder.EndEncoding();
        commandBuffer.Present(win.GetDrawable());
    }

    commandBuffer.Commit();
    commandBuffer.WaitUntilCompleted();
}

int main()
{
    const char shadersSrc[] = R"""(
        #include <metal_stdlib>
        using namespace metal;

        typedef struct
        {
            packed_float3 position;
            packed_float2 texcoord;
        } vertex_t;

        vertex float4 vertFunc(
            const device vertex_t* vertexArray [[buffer(0)]],
            unsigned int vID[[vertex_id]])
        {
            return float4(vertexArray[vID].position, 1.0);
        }

        fragment half4 fragFunc()
        {
            return half4(1.0, 0.0, 0.0, 1.0);
        }
    )""";

#if 0
    // Vertex shader outputs and per-fragment inputs. Includes clip-space position and vertex outputs
    //  interpolated by rasterizer and fed to each fragment generated by clip-space primitives.
    typedef struct
    {
        // The [[position]] attribute qualifier of this member indicates this value is the clip space
        //   position of the vertex wen this structure is returned from the vertex shader
        float4 clipSpacePosition [[position]];
        
        // Since this member does not have a special attribute qualifier, the rasterizer will
        //   interpolate its value with values of other vertices making up the triangle and
        //   pass that interpolated value to the fragment shader for each fragment in that triangle;
        float2 textureCoordinate;
        
    } RasterizerData;
    
    // Fragment function
    fragment float4
    samplingShader(RasterizerData in [[stage_in]],
                   texture2d<half> colorTexture [[texture(0)]])
    {
        constexpr sampler textureSampler (mag_filter::linear,
                                          min_filter::linear);
        
        // Sample the texture to obtain a color
        const half4 colorSample = colorTexture.sample(textureSampler, in.textureCoordinate);
        
        // We return the color of the texture
        return float4(colorSample);
    }
#endif
    
    // AAPLVertex improve;
    const float vertexData[] =
    {
         0.0f,  1.0f, 0.0f, 0.0f, 0.0f,
         1.0f, -1.0f, 0.0f, 0.0f, 0.0f,
        -1.0f, -1.0f, 0.0f, 0.0f, 0.0f,
    };
    g_device = mtlpp::Device::CreateSystemDefaultDevice();
    g_commandQueue = g_device.NewCommandQueue();

    mtlpp::Library library = g_device.NewLibrary(shadersSrc, mtlpp::CompileOptions(), nullptr);
    mtlpp::Function vertFunc = library.NewFunction("vertFunc");
    mtlpp::Function fragFunc = library.NewFunction("fragFunc");
    
    char pixels[16 * 16];
    int y, x;
    for (y = 0;  y < 16;  y++)
    {
        for (x = 0;  x < 16;  x++)
            pixels[y * 16 + x] = rand() % 256;
    }

    mtlpp::TextureDescriptor descriptor;
    descriptor.SetWidth(16);
    descriptor.SetHeight(16);
    descriptor.SetPixelFormat(mtlpp::PixelFormat::A8Unorm);

    // GL_CHECK(glTexImage2D(GL_TEXTURE_2D, 0, GL_LUMINANCE, 16, 16, 0, GL_LUMINANCE, GL_UNSIGNED_BYTE, pixels));
    // GL_CHECK(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST));
    // GL_CHECK(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST));

    g_texture = g_device.NewTexture(descriptor);
    assert(g_texture);
    mtlpp::Region region = { 0, 0, descriptor.GetWidth(), descriptor.GetHeight() };
    g_texture.Replace(region, 0, pixels, 16);
    g_vertexBuffer = g_device.NewBuffer(vertexData, sizeof(vertexData), mtlpp::ResourceOptions::CpuCacheModeDefaultCache);

    mtlpp::RenderPipelineDescriptor renderPipelineDesc;
    renderPipelineDesc.SetVertexFunction(vertFunc);
    renderPipelineDesc.SetFragmentFunction(fragFunc);
    renderPipelineDesc.GetColorAttachments()[0].SetPixelFormat(mtlpp::PixelFormat::BGRA8Unorm);
    g_renderPipelineState = g_device.NewRenderPipelineState(renderPipelineDesc, nullptr);

    Window win(g_device, &Render, 320, 240);
    Window::Run();

    return 0;
}

#endif
